server:
  port: 8080
spring:
  application:
    name: LoT-Back
  data:
    mongodb:
      username: root
      password: 123456
      host: localhost
      port: 27017
      database: LoTSystem
      authentication-database: admin
  mqtt:
    url: tcp://192.168.10.108:1883
    username: admin
    password: public
    client:
      id: java
